# Generated by Django 5.1.7 on 2026-03-25 15:28

import django.utils.timezone
from django.db import migrations, models


def copy_profile_auth_fields_to_user(apps, schema_editor):
    User = apps.get_model("auth_module", "User")
    UserProfile = apps.get_model("auth_module", "UserProfile")

    for profile in UserProfile.objects.select_related("user").all():
        normalized_phone = "".join(ch for ch in str(profile.mobile_number or "") if ch.isdigit()) or None
        normalized_chat_id = None
        raw_chat_id = str(profile.telegram_chat_id or "").strip()
        if raw_chat_id.lstrip("-").isdigit():
            normalized_chat_id = int(raw_chat_id)

        User.objects.filter(pk=profile.user_id).update(
            created_at=profile.user.date_joined,
            phone_number=normalized_phone,
            telegram_chat_id=normalized_chat_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_telegramlinksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(copy_profile_auth_fields_to_user, migrations.RunPython.noop),
    ]
